version: '3.0'


services:

  angular_contacts_api:
   image: avatsaev/angular-contacts-api:latest
   volumes:
     - './data:/app/data'
   ports:
     - '3000:3000'


  angular_contacts_client:
    build:
      context: .
      args:
        NG_PROJECT_NAME: angular-contacts
    ports:
      - '8000:80'
    links:
      - 'angular_contacts_api'
